export const IS_UPDATING_PROFILE_PICTURE = 'IS_UPDATING_PROFILE_PICTURE';
export const UPDATE_PROFILE_PICTURE_SUCCESS = 'UPDATE_PROFILE_PICTURE_SUCCESS';
export const UPDATE_PROFILE_PICTURE_FAILURE = 'UPDATE_PROFILE_PICTURE_FAILURE';
export const IS_UPDATING_PROFILE_BANNER = 'IS_UPDATING_PROFILE_BANNER';
export const UPDATE_PROFILE_BANNER_SUCCESS = 'UPDATE_PROFILE_BANNER_SUCCESS';
export const UPDATE_PROFILE_BANNER_FAILURE = 'UPDATE_PROFILE_BANNER_FAILURE';
