export const IS_FETCHING_USER_NOTIFICATIONS = 'IS_FETCHING_USER_NOTIFICATIONS';
export const FETCH_USER_NOTIFICATIONS_SUCCESS = 'FETCH_USER_NOTIFICATIONS_SUCCESS';
export const FETCH_USER_NOTIFICATIONS_FAILURE = 'FETCH_USER_NOTIFICATIONS_FAILURE';
export const IS_FETCHING_USER_NOTIFICATION = 'IS_FETCHING_USER_NOTIFICATION';
export const FETCH_USER_NOTIFICATION_SUCCESS = 'FETCH_USER_NOTIFICATION_SUCCESS';
export const FETCH_USER_NOTIFICATION_FAILURE = 'FETCH_USER_NOTIFICATION_FAILURE';
